### ISSUE TITLE
Tutorial on YOLOv4 Triton deployment

### ISSUE THREAD

**Issue by philipp-schmidt** [penolove/yolov4_triton_client#1]
Hi,

I recently wrote a full tutorial on how to deploy YOLOv4 on Triton and made a few improvements on the TensorRT engine from tensorrtx. Feel free to link this in your medium article and in this repo if you find it useful.

https://github.com/isarsoft/yolov4-triton-tensorrt

I'm planning to include python and C++ clients like you implemented them here soon.

**Comment by penolove** [comment]
thanks, it's great repo, and added the ref into the blog, looking forward to you guys awesome work.
